# Generated by Django 4.2.13 on 2024-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('APPETIZERS', 'Entrées'), ('MAIN_COURSES', 'Plats de résistance'), ('SIDE_DISHES', 'Accompagnements'), ('DESSERTS', 'Desserts'), ('BEVERAGES', 'Boissons'), ('SALADS', 'Salades'), ('SOUPS', 'Soupes'), ('SPECIALS', 'Plats du jour')], default='APPETIZERS', max_length=25),
        ),
    ]
